import pandas as pd
#1
s=pd.Series([1,2,93,4,5],index=['a','b','c','d','e'])
print(s)
print(type(s))
#2
d=pd.Series({"one":10,"two":20,"three":30},index={'one','two','three','a','b','c'})
print(d)
print(type(d))
#3
a=pd.Series([1,2,3,4,5,6,7,8,9])
b=pd.Series([11,12,13,14,15,16,17,18,19])
print(a[3],"\n")
print(a[-3:],"\n")
print(a[:5],"\n")
#4
print(a+10,"\n")
print(a+b,"\n")
#5
data=pd.DataFrame({"name":["radha","krishna"],"marks":[100,200]})
print(data,"\n")
print(type(data))
#6
iris=pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv")
print(iris.head(),"\n")
print(iris.tail(),"\n")
print(iris.shape)
print(iris.describe())
print(iris.iloc[0:3,0:2])
print(iris.loc[0:3],('sepal_length','petal_width','species'))
print(iris.drop('petal_width',axis=1))
print(iris.drop([120,121,123],axis=0))
print(iris.iloc[120:130,:].head())