import seaborn as sns
from matplotlib import pyplot as plt
sns.get_dataset_names()
data=sns.load_dataset('fmri')
data.head()
#1
sns.lineplot(x='timepoint',y='signal',data=data)
plt.show()
#2
sns.lineplot(x='timepoint',y='signal',data=data,hue='event')
plt.show()
#3
sns.lineplot(x='timepoint',y='signal',data=data,hue='event',style='event',markers=True)
plt.show()
#4
dim=sns.load_dataset('diamonds')
dim.head()
sns.barplot(x='cut',y='carat',data=dim)
plt.show()
#5
mpg=sns.load_dataset('mpg')
mpg.head()
sns.barplot(x='origin',y='horsepower',data=mpg)
plt.show()
#6
sns.barplot(x='origin',y='horsepower',data=mpg,palette='rocket') #sns.barplot(x='origin',y='horsepower',data=mpg,color='red')
plt.show()
#7
peng=sns.load_dataset('penguins')
peng.head()
sns.scatterplot(x='bill_depth_mm',y='flipper_length_mm',data=peng)
plt.show()
#8
sns.scatterplot(x='bill_depth_mm',y='flipper_length_mm',data=peng,hue='species',style='species')
plt.show()
#9
sns.scatterplot(x='bill_depth_mm',y='flipper_length_mm',data=peng,hue='bill_depth_mm')
plt.show()
#10
sns.distplot(dim['price'])
plt.show()
#11
sns.distplot(dim['price'],hist=False,color='green')   #sns.distplot(dim['price'],bin=10,color='green')
plt.show()
#12
iris=sns.load_dataset('iris')
iris.head()
sns.jointplot(x='sepal_length',y='petal_length',data=iris,hue='species')
plt.show()
#13
sns.jointplot(x='sepal_length',y='petal_length',data=iris,kind='reg')
plt.show()
#14
taxis=sns.load_dataset('taxis')
taxis.head()
sns.boxplot(x='payment',y='total',data=taxis)
plt.show()
#15
sns.boxplot(x='payment',y='distance',data=taxis)
plt.show()